"""Add hostDomain to gameInst

Revision ID: 215e6d73ab6a
Revises: 1c87e69cf5ab
Create Date: 2020-09-09 11:42:42.159479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215e6d73ab6a'
down_revision = '1c87e69cf5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_instance', sa.Column('hostDomain', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_instance', 'hostDomain')
    # ### end Alembic commands ###
