"""initial

Revision ID: 48cadd862c66
Revises: 
Create Date: 2020-09-08 20:34:02.519592

"""
from alembic import op
import sqlalchemy as sa
import application


# revision identifiers, used by Alembic.
revision = '48cadd862c66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('gameKey', sa.String(length=8), nullable=True),
    sa.Column('gameName', sa.String(length=40), nullable=True),
    sa.Column('gameSettings', application.models.sqldict.JSONEncodedDict(), nullable=True),
    sa.Column('gameState', application.models.sqldict.JSONEncodedDict(), nullable=True),
    sa.Column('gamePhase', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_instance_gameKey'), 'game_instance', ['gameKey'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_instance_gameKey'), table_name='game_instance')
    op.drop_table('game_instance')
    # ### end Alembic commands ###
