"""Add ArchivedGameInst.gameSettings

Revision ID: 778b5223801e
Revises: 7a4fc4ce34bb
Create Date: 2020-10-09 10:26:41.771955

"""
from alembic import op
import sqlalchemy as sa
import application


# revision identifiers, used by Alembic.
revision = '778b5223801e'
down_revision = '7a4fc4ce34bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_game_instance', sa.Column('gameSettings', application.models.sqldict.JSONEncodedDict(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archived_game_instance', 'gameSettings')
    # ### end Alembic commands ###
