"""Extend ArchivedGameInst

Revision ID: 7a4fc4ce34bb
Revises: a18dc38f8977
Create Date: 2020-10-08 20:55:23.443434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4fc4ce34bb'
down_revision = 'a18dc38f8977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_game_instance', sa.Column('customGameState1', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('customGameState2', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('customGameState3', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('customGameState4', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('customGameState5', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('customGameState6', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('customGameState7', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('customGameState8', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('isMultiDevice', sa.Boolean(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('isPlayer1LoggedIn', sa.Boolean(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('isPlayer2LoggedIn', sa.Boolean(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('isPlayer3LoggedIn', sa.Boolean(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('isPlayer4LoggedIn', sa.Boolean(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('player1Type', sa.String(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('player2Type', sa.String(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('player3Type', sa.String(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('player4Type', sa.String(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('result', sa.String(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('secondPlaceScore', sa.Integer(), nullable=True))
    op.add_column('archived_game_instance', sa.Column('winningScore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archived_game_instance', 'winningScore')
    op.drop_column('archived_game_instance', 'secondPlaceScore')
    op.drop_column('archived_game_instance', 'result')
    op.drop_column('archived_game_instance', 'player4Type')
    op.drop_column('archived_game_instance', 'player3Type')
    op.drop_column('archived_game_instance', 'player2Type')
    op.drop_column('archived_game_instance', 'player1Type')
    op.drop_column('archived_game_instance', 'isPlayer4LoggedIn')
    op.drop_column('archived_game_instance', 'isPlayer3LoggedIn')
    op.drop_column('archived_game_instance', 'isPlayer2LoggedIn')
    op.drop_column('archived_game_instance', 'isPlayer1LoggedIn')
    op.drop_column('archived_game_instance', 'isMultiDevice')
    op.drop_column('archived_game_instance', 'customGameState8')
    op.drop_column('archived_game_instance', 'customGameState7')
    op.drop_column('archived_game_instance', 'customGameState6')
    op.drop_column('archived_game_instance', 'customGameState5')
    op.drop_column('archived_game_instance', 'customGameState4')
    op.drop_column('archived_game_instance', 'customGameState3')
    op.drop_column('archived_game_instance', 'customGameState2')
    op.drop_column('archived_game_instance', 'customGameState1')
    # ### end Alembic commands ###
